Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,7 +1,20 @@
-stages:
-  - deploy
-
-deploy:
-  stage: deploy
+# This file is a template, and might need editing before it works on your project.
+# Publishes a tag/branch to Composer Packages of the current project
+publish:
+  image: php/microservice:latest
+  stage: build
+  variables:
+    URL: "https://gitlab.05.ru/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
   script:
-    - Invoke-WebRequest -uri "https://__token__:z1FzU2dDFkhrxFny1raB@gitlab.05.ru/api/v4/projects/39/packages/composer" -Method Post -Body @{branch='master'}
+    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
+    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
+    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
+    - code=$(echo "$response" | tail -n 1)
+    - body=$(echo "$response" | head -n 1)
+    # Output state information
+    - if [ $code -eq 201 ]; then
+        echo "Package created - Code $code - $body";
+      else
+        echo "Could not create package - Code $code - $body";
+        exit 1;
+      fi
